server:
  port: 8001

spring:
  application:
    name: cloud-payment-service # 给ApplicationContext命名，以生成ID作为区分
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/score?useUnicode=true&characterEncoding=utf-8&userSSL=false
    username: root
    password: 123456


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.buaa.backkom.cloud.entities



eureka:
  client:
    #是否抓取Eureka注册中心的注册信息
    fetchRegistry: true
    #是否注册到eurekaServer中
    register-with-eureka: true
    #eurekaServer通信地址
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true